defmodule Pigpiox.Command do
  @moduledoc false

  @commands %{
    set_mode: 0,
    get_mode: 1,
    gpio_read: 3,
    gpio_write: 4,
    set_servo_pulsewidth: 8,
    notify_open: 18,
    notify_begin: 19,
    notify_pause: 20,
    notify_close: 21,
    get_servo_pulsewidth: 84,
    hardware_clk: 85,
    hardware_pwm: 86,
    waveform_clear_all: 27,
    waveform_add_generic: 28,
    waveform_add_serial: 29,
    waveform_busy: 32,
    waveform_stop: 33,
    waveform_get_micros: 34,
    waveform_get_pulses: 35,
    waveform_get_cbs: 36,
    waveform_create: 49,
    waveform_delete: 50,
    waveform_transmit_once: 51,
    waveform_transmit_repeat: 52,
    waveform_chain: 93,
    waveform_transmit_mode: 100,
    waveform_current: 101,
    get_PWM_dutycycle: 83,
    get_PWM_frequency: 23,
    set_PWM_frequency: 7,
    get_PWM_range: 22,
    set_PWM_range: 6,
    gpio_PWM: 5
  }
  @command_names Map.keys(@commands)

  @spec code(atom) :: pos_integer
  def code(command) when command in @command_names do
    @commands[command]
  end

  @error_code_map %{
    -1 => :init_failed,
    -2 => :bad_user_gpio,
    -3 => :bad_gpio,
    -4 => :bad_mode,
    -5 => :bad_level,
    -6 => :bad_pud,
    -7 => :bad_pulsewidth,
    -8 => :bad_dutycycle,
    -9 => :bad_timer,
    -10 => :bad_ms,
    -11 => :bad_timetype,
    -12 => :bad_seconds,
    -13 => :bad_micros,
    -14 => :timer_failed,
    -15 => :bad_wdog_timeout,
    -16 => :no_alert_func,
    -17 => :bad_clk_periph,
    -18 => :bad_clk_source,
    -19 => :bad_clk_micros,
    -20 => :bad_buf_millis,
    -21 => :bad_dutyrange,
    -22 => :bad_signum,
    -23 => :bad_pathname,
    -24 => :no_handle,
    -25 => :bad_handle,
    -26 => :bad_if_flags,
    -27 => :bad_channel,
    -28 => :bad_prim_channel,
    -29 => :bad_socket_port,
    -30 => :bad_fifo_command,
    -31 => :bad_seco_channel,
    -32 => :not_initialised,
    -33 => :initialised,
    -34 => :bad_wave_mode,
    -35 => :bad_cfg_internal,
    -36 => :bad_wave_baud,
    -37 => :too_many_pulses,
    -38 => :too_many_chars,
    -39 => :not_serial_gpio,
    -40 => :bad_serial_struc,
    -41 => :bad_serial_buf,
    -42 => :not_permitted,
    -43 => :some_permitted,
    -44 => :bad_wvsc_commnd,
    -45 => :bad_wvsm_commnd,
    -46 => :bad_wvsp_commnd,
    -47 => :bad_pulselen,
    -48 => :bad_script,
    -49 => :bad_script_id,
    -50 => :bad_ser_offset,
    -51 => :gpio_in_use,
    -52 => :bad_serial_count,
    -53 => :bad_param_num,
    -54 => :dup_tag,
    -55 => :too_many_tags,
    -56 => :bad_script_cmd,
    -57 => :bad_var_num,
    -58 => :no_script_room,
    -59 => :no_memory,
    -60 => :sock_read_failed,
    -61 => :sock_writ_failed,
    -62 => :too_many_param,
    -63 => :script_not_ready,
    -64 => :bad_tag,
    -65 => :bad_mics_delay,
    -66 => :bad_mils_delay,
    -67 => :bad_wave_id,
    -68 => :too_many_cbs,
    -69 => :too_many_ool,
    -70 => :empty_waveform,
    -71 => :no_waveform_id,
    -72 => :i2c_open_failed,
    -73 => :ser_open_failed,
    -74 => :spi_open_failed,
    -75 => :bad_i2c_bus,
    -76 => :bad_i2c_addr,
    -77 => :bad_spi_channel,
    -78 => :bad_flags,
    -79 => :bad_spi_speed,
    -80 => :bad_ser_device,
    -81 => :bad_ser_speed,
    -82 => :bad_param,
    -83 => :i2c_write_failed,
    -84 => :i2c_read_failed,
    -85 => :bad_spi_count,
    -86 => :ser_write_failed,
    -87 => :ser_read_failed,
    -88 => :ser_read_no_data,
    -89 => :unknown_command,
    -90 => :spi_xfer_failed,
    -91 => :bad_pointer,
    -92 => :no_aux_spi,
    -93 => :not_pwm_gpio,
    -94 => :not_servo_gpio,
    -95 => :not_hclk_gpio,
    -96 => :not_hpwm_gpio,
    -97 => :bad_hpwm_freq,
    -98 => :bad_hpwm_duty,
    -99 => :bad_hclk_freq,
    -100 => :bad_hclk_pass,
    -101 => :hpwm_illegal,
    -102 => :bad_databits,
    -103 => :bad_stopbits,
    -104 => :msg_toobig,
    -105 => :bad_malloc_mode,
    -106 => :too_many_segs,
    -107 => :bad_i2c_seg,
    -108 => :bad_smbus_cmd,
    -109 => :not_i2c_gpio,
    -110 => :bad_i2c_wlen,
    -111 => :bad_i2c_rlen,
    -112 => :bad_i2c_cmd,
    -113 => :bad_i2c_baud,
    -114 => :chain_loop_cnt,
    -115 => :bad_chain_loop,
    -116 => :chain_counter,
    -117 => :bad_chain_cmd,
    -118 => :bad_chain_delay,
    -119 => :chain_nesting,
    -120 => :chain_too_big,
    -121 => :deprecated,
    -122 => :bad_ser_invert,
    -123 => :bad_edge,
    -124 => :bad_isr_init,
    -125 => :bad_forever,
    -126 => :bad_filter,
    -127 => :bad_pad,
    -128 => :bad_strength,
    -129 => :fil_open_failed,
    -130 => :bad_file_mode,
    -131 => :bad_file_flag,
    -132 => :bad_file_read,
    -133 => :bad_file_write,
    -134 => :file_not_ropen,
    -135 => :file_not_wopen,
    -136 => :bad_file_seek,
    -137 => :no_file_match,
    -138 => :no_file_access,
    -139 => :file_is_a_dir,
    -140 => :bad_shell_status,
    -141 => :bad_script_name,
    -142 => :bad_spi_baud,
    -143 => :not_spi_gpio,
    -144 => :bad_event_id
  }

  @spec error_reason(neg_integer) :: :atom
  def error_reason(code) do
    @error_code_map[code] || :unknown_error
  end
end
